package dev;

public enum msgType{
	LOGIN_REQUEST,
	LOGOUT_REQUEST,
	USER_REQUEST,
	USER_EDIT,
	AUTHUSER_REQUEST,
	AUTHUSER_EDIT,
	AUTHUSER_DELETE,
	PWRESET_REQUEST,
	ACCOUNT_CREATE,
	ACCOUNT_CLOSE,
	ACCOUNTS_REQUEST,
	ACCOUNT_REQUEST,
	ACCOUNTS_FREEZE,
	WITHDRAWAL_REQUEST,
	DEPOSIT_REQUEST,
	TRANSFER_REQUEST,
	USER_CREATE,
	TRANSACTIONS_REQUEST
}